/* =========================================================
   Lindsey Street District — business directory data
   ---------------------------------------------------------
   Auto-generated from the district business spreadsheet.
   Safe to hand-edit. To add a business, copy a block in
   BUSINESSES and fill in the fields (blank fields are hidden).
   `category` must match a key in CATEGORIES below.
   Map pins are placed automatically from the street address
   (see approxCoords() in app.js); positions are APPROXIMATE.
   Add explicit  lat: 35.xx, lng: -97.xx  to a business to
   pin it precisely.
   ========================================================= */

const CATEGORIES = {
  food: { label: "Food", emoji: "\ud83c\udf7d\ufe0f" },
  service: { label: "Services", emoji: "\ud83d\udee0\ufe0f" },
  beauty: { label: "Health & Beauty", emoji: "\ud83d\udc87" },
  shop: { label: "Shops", emoji: "\ud83d\udecd\ufe0f" },
  auto: { label: "Automotive", emoji: "\ud83d\udd27" },
  bank: { label: "Banks & Finance", emoji: "\ud83c\udfe6" },
  smoke: { label: "Smoke & Vape", emoji: "\ud83d\udca8" },
  gym: { label: "Fitness", emoji: "\ud83c\udfcb\ufe0f" },
  fun: { label: "Entertainment", emoji: "\ud83c\udfb6" },
  civic: { label: "Civic", emoji: "\ud83c\udfdb\ufe0f" },
  education: { label: "Education", emoji: "\ud83d\udcda" },
  pets: { label: "Pets", emoji: "\ud83d\udc3e" },
  worship: { label: "Worship", emoji: "\u26ea" }
};

const BUSINESSES = [
  {"name": "McGee Street Animal Hospital", "category": "pets", "address": "1140 McGee, Norman, OK"},
  {"name": "Flawless Auto Center", "category": "auto", "address": "1209 W Lindsey, Norman, OK"},
  {"name": "Ron's Automotive", "category": "auto", "address": "1215 24th Ave SW, Norman, OK"},
  {"name": "Mike's Tire & Auto", "category": "auto", "address": "1802 W Lindsey, Norman, OK"},
  {"name": "Well's Automotive", "category": "auto", "address": "1901 W Lindsey, Norman, OK"},
  {"name": "Mr. Short Stop", "category": "auto", "address": "2007 W Lindsey, Norman, OK"},
  {"name": "O'Reilly Auto Parts", "category": "auto", "address": "2113 W Lindsey, Norman, OK"},
  {"name": "Best of Imports", "category": "auto", "address": "2114 W Lindsey, Norman, OK"},
  {"name": "OK Fast Lube", "category": "auto", "address": "2201 W Lindsey, Norman, OK"},
  {"name": "Midas", "category": "auto", "address": "2206 W Lindsey, Norman, OK"},
  {"name": "Casey's", "category": "auto", "address": "2316 W Lindsey, Norman, OK"},
  {"name": "True Sky Credit Union", "category": "bank", "address": "1212 W Lindsey, Norman, OK"},
  {"name": "Security Finance Loans", "category": "bank", "address": "1213 W Lindsey, Norman, OK", "center": "Lindsey Park Center"},
  {"name": "Continental Credit Loans", "category": "bank", "address": "1221 W Lindsey, Norman, OK", "center": "Lindsey Park Center"},
  {"name": "First Fidelity Bank", "category": "bank", "address": "1337 W Lindsey, Norman, OK"},
  {"name": "Arvest Bank", "category": "bank", "address": "1355 W Lindsey, Norman, OK"},
  {"name": "OU Federal Credit Union", "category": "bank", "address": "2000 W Lindsey, Norman, OK"},
  {"name": "Red River Credit Corporation", "category": "bank", "address": "2102 W Lindsey #B, Norman, OK", "center": "West Lindsey Center"},
  {"name": "Regional Finance", "category": "bank", "address": "2108 W Lindsey #A, Norman, OK", "center": "West Lindsey Center"},
  {"name": "CON Investigation Center", "category": "civic", "address": "1507 W Lindsey, Norman, OK"},
  {"name": "Mine Safety and Health Administration", "category": "civic", "address": "2227 W Lindsey #1450, Norman, OK", "center": "Westoaks Office Park"},
  {"name": "KISS Institute for Practical Robotics", "category": "education", "address": "1818 W Lindsey D180, Norman, OK", "center": "Lindsey Square", "phone": "(405) 579-4609", "email": "info@kipr.org", "website": "https://www.kipr.org/", "facebook": "https://www.facebook.com/BotballRobotics/", "instagram": "https://www.instagram.com/botballrobotics"},
  {"name": "Happy Monk", "category": "fun", "address": "1430 W Lindsey, Norman, OK", "center": "Opies"},
  {"name": "Oklahoma Tickets", "category": "fun", "address": "2215 W Lindsey #200, Norman, OK", "center": "Westoaks Office Park"},
  {"name": "Hal Smith Restaurant (Coming Soon)", "category": "food", "address": "1035 S Berry, Norman, OK"},
  {"name": "Penny Hill", "category": "food", "address": "1150 W Lindsey, Norman, OK"},
  {"name": "Starbucks", "category": "food", "address": "1200 W Lindsey, Norman, OK"},
  {"name": "Taqueria La Chiva", "category": "food", "address": "1209 W Lindsey, Norman, OK"},
  {"name": "Donut King", "category": "food", "address": "1214 W Lindsey, Norman, OK"},
  {"name": "Subway", "category": "food", "address": "1222 W Lindsey, Norman, OK"},
  {"name": "Legends", "category": "food", "address": "1313 W Lindsey, Norman, OK"},
  {"name": "Legends Times Two", "category": "food", "address": "1333 W Lindsey, Norman, OK"},
  {"name": "El Sombrero", "category": "food", "address": "1424 W Lindsey, Norman, OK"},
  {"name": "Velvet Taco", "category": "food", "address": "1440 W Lindsey, Norman, OK"},
  {"name": "Pizza Shuttle", "category": "food", "address": "1506 W Lindsey, Norman, OK"},
  {"name": "Ray's BBQ", "category": "food", "address": "1514 W Lindsey, Norman, OK"},
  {"name": "Classic 50's", "category": "food", "address": "1521 W Lindsey, Norman, OK"},
  {"name": "Mr. Hui", "category": "food", "address": "1522 W Lindsey, Norman, OK"},
  {"name": "McDonald's", "category": "food", "address": "1720 W Lindsey, Norman, OK", "center": "Hollywood Shopping Center"},
  {"name": "Beanstalk Sno", "category": "food", "address": "1724 W Lindsey, Norman, OK", "center": "Hollywood Shopping Center"},
  {"name": "Sonic", "category": "food", "address": "1730 W Lindsey, Norman, OK"},
  {"name": "KFC", "category": "food", "address": "1801 W Lindsey, Norman, OK"},
  {"name": "HTeaO", "category": "food", "address": "1807 W Lindsey, Norman, OK"},
  {"name": "Teapioca", "category": "food", "address": "1808 W Lindsey #300, Norman, OK", "center": "Jackson Square"},
  {"name": "Krave Teriyaki", "category": "food", "address": "1808 W Lindsey #400, Norman, OK", "center": "Jackson Square"},
  {"name": "Eagle One Pizza", "category": "food", "address": "1951 W Lindsey, Norman, OK", "center": "Heritage Plaza"},
  {"name": "Level 10 Nutrition", "category": "food", "address": "1959 W Lindsey, Norman, OK", "center": "Heritage Plaza"},
  {"name": "Artisan Meats", "category": "food", "address": "1965 W Lindsey, Norman, OK", "center": "Heritage Plaza"},
  {"name": "Volcano", "category": "food", "address": "2030 W Lindsey, Norman, OK"},
  {"name": "The Fix Energy & Nutrition Lounge", "category": "food", "address": "2100 W Lindsey #104, Norman, OK", "center": "West Lindsey Center"},
  {"name": "India Village", "category": "food", "address": "2110 W Lindsey, Norman, OK"},
  {"name": "Lupita's Mexican Food", "category": "food", "address": "2108 W Lindsey #B, Norman, OK"},
  {"name": "Taco Bell", "category": "food", "address": "2125 W Lindsey, Norman, OK"},
  {"name": "Del Rancho", "category": "food", "address": "2300 W Lindsey, Norman, OK"},
  {"name": "El Chapin", "category": "food", "address": "2305 W Lindsey #107, Norman, OK", "center": "Rahimi Plaza"},
  {"name": "Corkscrew Wine", "category": "food", "address": "2319 W Lindsey, Norman, OK"},
  {"name": "Press & Plow", "category": "food", "address": "800 W Lindsey, Norman, OK"},
  {"name": "Koda CrossFit", "category": "gym", "address": "1210 McGee, Norman, OK"},
  {"name": "Fight or Flight Fitness", "category": "gym", "address": "1309 24th Ave SW, Norman, OK"},
  {"name": "Downtown Fitness", "category": "gym", "address": "1610 W Lindsey, Norman, OK", "center": "Hollywood Shopping Center"},
  {"name": "Vin's Styling", "category": "beauty", "address": "1300 McGee #130, Norman, OK", "center": "Hilltop"},
  {"name": "Sooner Pharmacy", "category": "beauty", "address": "1811 W Lindsey, Norman, OK"},
  {"name": "Nail Boutique", "category": "beauty", "address": "1932 W Lindsey #H, Norman, OK", "center": "Clarendon Park Shopping Center"},
  {"name": "KEDPLASMA", "category": "beauty", "address": "2101 W Lindsey, Norman, OK"},
  {"name": "Native Stylz Salon", "category": "beauty", "address": "1212 S Berry, Norman, OK"},
  {"name": "The Mane Man", "category": "beauty", "address": "1215 W Lindsey, Norman, OK", "center": "Lindsey Park Center"},
  {"name": "MM Salon Spa", "category": "beauty", "address": "1217 W Lindsey, Norman, OK", "center": "Lindsey Park Center"},
  {"name": "Savvy Nails", "category": "beauty", "address": "1630 W Lindsey, Norman, OK", "center": "Hollywood Shopping Center"},
  {"name": "Hair Co Salon", "category": "beauty", "address": "1632 W Lindsey, Norman, OK", "center": "Hollywood Shopping Center"},
  {"name": "Integrative Health Center Massage & Spa", "category": "beauty", "address": "1634 W Lindsey, Norman, OK", "center": "Hollywood Shopping Center"},
  {"name": "Karen Barnalace Aesthetics", "category": "beauty", "address": "1636 W Lindsey, Norman, OK", "center": "Hollywood Shopping Center"},
  {"name": "Massage Therapy Norman", "category": "beauty", "address": "1300 McGee #100A, Norman, OK", "center": "Hilltop"},
  {"name": "Fade N Up", "category": "beauty", "address": "1955 W Lindsey, Norman, OK", "center": "Heritage Plaza"},
  {"name": "Lifetime Dental of Norman", "category": "beauty", "address": "2001 W Lindsey, Norman, OK"},
  {"name": "Sooner Urgent Care", "category": "beauty", "address": "2100 W Lindsey #106, Norman, OK", "center": "West Lindsey Center"},
  {"name": "Chinese Relax Massage", "category": "beauty", "address": "2305 W Lindsey #123, Norman, OK", "center": "Rahimi Plaza"},
  {"name": "Skills for Living", "category": "beauty", "address": "1818 W Lindsey C248, Norman, OK", "center": "Lindsey Square", "phone": "405-360-5554", "website": "https://www.skillsforliving.net/"},
  {"name": "Bright Start", "category": "service", "address": "1212 McGee, Norman, OK"},
  {"name": "Julia's Dance Academy", "category": "service", "address": "1229 W Lindsey, Norman, OK", "center": "Lindsey Park Center"},
  {"name": "Dale K. Graham Veterans Foundation", "category": "service", "address": "1233 W Lindsey, Norman, OK", "center": "Lindsey Park Center"},
  {"name": "Lanoy Tag Agency", "category": "service", "address": "1315 24th Ave SW, Norman, OK"},
  {"name": "All Around Tattoo", "category": "service", "address": "1430 W Lindsey #K, Norman, OK", "center": "Opies"},
  {"name": "Star Kids", "category": "service", "address": "1600 W Lindsey, Norman, OK", "center": "Hollywood Shopping Center"},
  {"name": "Titan Martial Arts", "category": "service", "address": "1704 W Lindsey, Norman, OK", "center": "Hollywood Shopping Center"},
  {"name": "UpperCrust Food Service", "category": "service", "address": "1712 W Lindsey, Norman, OK", "center": "Hollywood Shopping Center"},
  {"name": "Hollywood Coin Laundry", "category": "service", "address": "1746 W Lindsey, Norman, OK", "center": "Hollywood Shopping Center"},
  {"name": "Dowell Properties", "category": "service", "address": "1932 W Lindsey #A, Norman, OK", "center": "Clarendon Park Shopping Center"},
  {"name": "Enhanced Benefits Solutions", "category": "service", "address": "1932 W Lindsey #B, Norman, OK", "center": "Clarendon Park Shopping Center"},
  {"name": "Farmers Insurance – Josh Jacks", "category": "service", "address": "1932 W Lindsey #C, Norman, OK", "center": "Clarendon Park Shopping Center"},
  {"name": "In Home TV Repair", "category": "service", "address": "1932 W Lindsey #D, Norman, OK", "center": "Clarendon Park Shopping Center"},
  {"name": "Love Alterations", "category": "service", "address": "1932 W Lindsey #E, Norman, OK", "center": "Clarendon Park Shopping Center"},
  {"name": "Metro Brokers Connect Team", "category": "service", "address": "1932 W Lindsey #F, Norman, OK", "center": "Clarendon Park Shopping Center"},
  {"name": "Shelter Insurance – JD Johnson", "category": "service", "address": "1932 W Lindsey #G, Norman, OK", "center": "Clarendon Park Shopping Center"},
  {"name": "Precision Garage Door of Norman", "category": "service", "address": "2100 W Lindsey #100, Norman, OK", "center": "West Lindsey Center"},
  {"name": "Boost Mobile", "category": "service", "address": "2100 W Lindsey #102, Norman, OK", "center": "West Lindsey Center"},
  {"name": "Oklahoma's Finest Electric, Heating & Air", "category": "service", "address": "2215 W Lindsey #109, Norman, OK", "center": "Westoaks Office Park"},
  {"name": "Sooner Traditions", "category": "service", "address": "2221 W Lindsey #201, Norman, OK", "center": "Westoaks Office Park"},
  {"name": "Legal Aid Services of Oklahoma", "category": "service", "address": "2227 W Lindsey #1550, Norman, OK", "center": "Westoaks Office Park"},
  {"name": "I-Drive", "category": "service", "address": "2233 W Lindsey #117, Norman, OK", "center": "Westoaks Office Park"},
  {"name": "South Central CASA of Oklahoma", "category": "service", "address": "2241 W Lindsey #500, Norman, OK", "center": "Westoaks Office Park"},
  {"name": "Cricket Wireless", "category": "service", "address": "2305 W Lindsey #111, Norman, OK", "center": "Rahimi Plaza"},
  {"name": "Metro by T-Mobile", "category": "service", "address": "2305 W Lindsey #119, Norman, OK", "center": "Rahimi Plaza"},
  {"name": "Henson & Huffman", "category": "service", "address": "1820 W Lindsey #100, Norman, OK", "center": "Lindsey Square"},
  {"name": "DaVita Dialysis Center", "category": "service", "address": "1818 W Lindsey B104, Norman, OK", "center": "Lindsey Square"},
  {"name": "Oklahoma Hypnosis Centers", "category": "service", "address": "1818 W Lindsey C120, Norman, OK", "center": "Lindsey Square", "phone": "(405) 956-5098", "email": "vicky@oklahomahypnosiscenters.com", "website": "https://www.oklahomahypnosiscenters.com/"},
  {"name": "Susan Beyer, CPA", "category": "service", "address": "1818 W Lindsey C140, Norman, OK", "center": "Lindsey Square", "phone": "405-620-5396", "email": "susanbeyer@normantax.com", "website": "https://www.normantax.com/"},
  {"name": "Peace Homecare", "category": "service", "address": "1818 W Lindsey C180, Norman, OK", "center": "Lindsey Square", "phone": "(405) 701-5951", "email": "info@peacehomecare.net", "website": "https://www.peacehomecare.net/", "facebook": "https://www.facebook.com/peacehomecareincok/", "instagram": "https://www.instagram.com/peacehome2020/"},
  {"name": "Rietta Miller, Social Worker", "category": "service", "address": "1818 W Lindsey C210, Norman, OK", "center": "Lindsey Square", "phone": "(405) 831-6388"},
  {"name": "Cleveland County GOP", "category": "civic", "address": "1818 W Lindsey B108, Norman, OK", "center": "Lindsey Square", "phone": "(405) 701-9655", "email": "clevelandcountyrepublicanparty@gmail.com", "website": "https://www.ccgopok.com/", "facebook": "https://www.facebook.com/clevelandcountygop/"},
  {"name": "United Energy Drilling", "category": "service", "address": "1818 W Lindsey C100, Norman, OK", "center": "Lindsey Square", "phone": "(405) 482-0080", "email": "lisa@ued-ok.com", "website": "https://unitedenergydrilling.com", "facebook": "https://facebook.com/UEDOK"},
  {"name": "Homeland", "category": "shop", "address": "1724 W Lindsey, Norman, OK", "center": "Hollywood Shopping Center"},
  {"name": "Dollar General", "category": "shop", "address": "1221 W Lindsey, Norman, OK"},
  {"name": "Dollar Tree", "category": "shop", "address": "1614 W Lindsey, Norman, OK", "center": "Hollywood Shopping Center"},
  {"name": "International Pantry", "category": "shop", "address": "1618 W Lindsey, Norman, OK", "center": "Hollywood Shopping Center"},
  {"name": "Rainbow Cleaning Systems", "category": "shop", "address": "1622 W Lindsey, Norman, OK", "center": "Hollywood Shopping Center"},
  {"name": "Mattress By Appointment", "category": "shop", "address": "1628 W Lindsey, Norman, OK", "center": "Hollywood Shopping Center"},
  {"name": "Assist Wireless", "category": "shop", "address": "1744 W Lindsey, Norman, OK", "center": "Hollywood Shopping Center"},
  {"name": "Salvation Army", "category": "shop", "address": "1742 W Lindsey, Norman, OK", "center": "Hollywood Shopping Center"},
  {"name": "Heat4yaFeet", "category": "shop", "address": "1953 W Lindsey, Norman, OK", "center": "Heritage Plaza"},
  {"name": "Christie's Toy Box", "category": "shop", "address": "2106 W Lindsey, Norman, OK", "center": "West Lindsey Center"},
  {"name": "Christmas Expressions", "category": "shop", "address": "2214 W Lindsey, Norman, OK"},
  {"name": "Meds and Wares", "category": "smoke", "address": "1404 W Lindsey, Norman, OK"},
  {"name": "TNT Vapes", "category": "smoke", "address": "1225 W Lindsey, Norman, OK", "center": "Lindsey Park Center"},
  {"name": "Lotus Botanicals CBD & Kratom", "category": "smoke", "address": "1714 W Lindsey, Norman, OK", "center": "Hollywood Shopping Center"},
  {"name": "Vapor Lax", "category": "smoke", "address": "1808 W Lindsey #100, Norman, OK", "center": "Jackson Square"},
  {"name": "Cronic Solutions", "category": "smoke", "address": "1808 W Lindsey #200, Norman, OK", "center": "Jackson Square"},
  {"name": "Xclusive Cannabis", "category": "smoke", "address": "2102 W Lindsey #A, Norman, OK", "center": "West Lindsey Center"},
  {"name": "How High", "category": "smoke", "address": "2118 W Lindsey, Norman, OK"},
  {"name": "Bethel Baptist Church", "category": "worship", "address": "1717 W Lindsey, Norman, OK"}
];

/* Upcoming district events — edit freely. */
const EVENTS = [
  {"month": "AUG", "day": "16", "title": "First Friday Sidewalk Stroll", "when": "Fri · 6–9pm", "desc": "Shops stay open late with sidewalk sales, live music, and food trucks along Lindsey."},
  {"month": "SEP", "day": "06", "title": "Fall Kickoff Block Party", "when": "Sat · 11am–4pm", "desc": "Celebrate game-day season with local vendors, giveaways, and family fun."},
  {"month": "OCT", "day": "25", "title": "District Trick-or-Treat", "when": "Sat · 3–6pm", "desc": "Costumes welcome — collect treats up and down the district."}
];

/* Map center + zoom (W Lindsey St corridor, Norman OK). */
const MAP_CONFIG = { center: [35.2045, -97.4655], zoom: 15 };
